(() => {
  const $ = s => document.querySelector(s);
  const state = { user:null, sessions:[], current:null, authMode:'login', local:false, source:null, uploaded:null };
  const api = async (path, opts={}) => { const r=await fetch('/api'+path,{credentials:'include',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}}); let d={}; try{d=await r.json()}catch{} if(!r.ok) throw new Error(d.error||`Request gagal (${r.status})`); return d; };
  const toast = msg => { const el=$('#toast'); el.textContent=msg; el.classList.remove('hidden'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.add('hidden'),2600); };
  const esc = s => String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const time = ts => {if(!ts)return '';const d=new Date(ts), now=new Date();return d.toDateString()===now.toDateString()?d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString('id-ID',{day:'2-digit',month:'short'});};
  function setConnection(ok){const e=$('#connection');e.innerHTML=ok?'<i class="w-2 h-2 rounded-full bg-emerald-400"></i> Terhubung':'<i class="w-2 h-2 rounded-full bg-amber-400"></i> Mode lokal';}
  function renderSessions(){const q=$('#search').value.toLowerCase();const items=state.sessions.filter(s=>(s.name||'Percakapan baru').toLowerCase().includes(q));$('#session-count').textContent=state.sessions.length;$('#sessions').innerHTML=items.map(s=>`<button class="session ${s.id===state.current?'active':''}" data-id="${esc(s.id)}"><span class="text-violet">${s.pinned?'◆':'◇'}</span><span class="session-title">${esc(s.name||'Percakapan baru')}</span><span class="session-time">${time(s.lastUsed||s.createdAt)}</span></button>`).join('')||'<div class="px-3 py-8 text-center text-xs text-slate-600">Belum ada percakapan</div>';document.querySelectorAll('.session').forEach(x=>x.onclick=()=>switchSession(x.dataset.id));}
  function openChat(){ $('#welcome').classList.add('hidden');$('#chat').classList.remove('hidden'); }
  function addMessage(role,text){openChat();const wrap=document.createElement('div');wrap.className=`message ${role}`;wrap.innerHTML=`<div class="flex items-center gap-2 mb-2 text-[11px] text-slate-500">${role==='user'?'Anda':'Dinda'}</div><div class="bubble ${role==='user'?'user':'ai'}">${esc(text)}</div>`;$('#messages').append(wrap);$('#chat').scrollTop=$('#chat').scrollHeight;return wrap.querySelector('.bubble');}
  async function loadMe(){try{const d=await api('/me');if(d.authed){state.user=d.user;setConnection(true);$('#profile').textContent=(d.user.name||d.user.username||'?')[0].toUpperCase();$('#logout').classList.remove('hidden');await loadSessions();return true}}catch(e){} setConnection(false);return false;}
  async function loadSessions(){try{const d=await api('/sessions');state.sessions=d.sessions||[];renderSessions()}catch(e){state.local=true;renderSessions()}}
  async function switchSession(id){state.current=id;renderSessions();openChat();$('#messages').innerHTML='';try{const d=await api('/sessions/'+encodeURIComponent(id)+'/messages',{method:'POST'});(d.messages||[]).forEach(m=>addMessage(m.role==='user'?'user':'ai',m.content||m.text||''));}catch(e){toast('Riwayat belum dapat dimuat')}}
  async function newChat(){try{const d=await api('/sessions',{method:'POST',body:JSON.stringify({name:'Percakapan baru'})});state.sessions.unshift(d.session||d);state.current=(d.session||d).id;renderSessions();$('#messages').innerHTML='';openChat()}catch(e){state.current='local-'+Date.now();state.sessions.unshift({id:state.current,name:'Percakapan baru',createdAt:Date.now()});renderSessions();$('#messages').innerHTML='';openChat()}}
  async function send(text){text=(text||$('#prompt').value).trim();if(!text)return;$('#prompt').value='';$('#prompt').style.height='auto';addMessage('user',text);$('#typing').classList.remove('hidden');$('#send').disabled=true;if(!state.current)await newChat();try{const d=await api('/chat',{method:'POST',body:JSON.stringify({message:text,sessionId:state.current,modelId:$('#model').value||undefined})});$('#typing').classList.add('hidden');if(d.answer||d.text)addMessage('ai',d.answer||d.text);else connectStream();}catch(e){$('#typing').classList.add('hidden');addMessage('ai','Terjadi kendala saat menghubungi backend: '+e.message);setConnection(false)}finally{$('#send').disabled=false}}
  function connectStream(){if(state.source)state.source.close();state.source=new EventSource('/api/events');let bubble=null;state.source.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='text'||d.type==='delta'||d.delta){if(!bubble)bubble=addMessage('ai','');bubble.textContent+=(d.delta||d.text||'');$('#chat').scrollTop=$('#chat').scrollHeight}if(['agent_end','done','error'].includes(d.type)){state.source.close();$('#typing').classList.add('hidden');$('#send').disabled=false}}catch{}};state.source.onerror=()=>{$('#typing').classList.add('hidden');state.source.close();$('#send').disabled=false}}
  function showAuth(){ $('#auth').classList.remove('hidden');$('#auth-error').textContent='';$('#auth-title').textContent=state.authMode==='login'?'Masuk ke workspace':'Buat akun baru';$('#auth-name').classList.toggle('hidden',state.authMode==='login');$('#auth-switch').textContent=state.authMode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk'; }
  async function auth(e){e.preventDefault();const username=$('#auth-user').value.trim(),password=$('#auth-pass').value;try{const d=await api(state.authMode==='login'?'/login':'/register',{method:'POST',body:JSON.stringify({username,password,name:$('#auth-name').value.trim()})});state.user=d.user;$('#auth').classList.add('hidden');await loadMe();toast('Selamat datang di COBLAI')}catch(err){$('#auth-error').textContent=err.message}}
  $('#new-chat').onclick=$('#new-chat-top').onclick=newChat;$('#send').onclick=e=>{e.preventDefault();send()};$('#composer').onsubmit=e=>{e.preventDefault();send()};$('#prompt').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,160)+'px'};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};document.querySelectorAll('.starter').forEach(b=>b.onclick=()=>{ $('#prompt').value=b.dataset.prompt;$('#prompt').focus()});$('#search').oninput=renderSessions;$('#menu').onclick=()=>$('#sidebar').classList.toggle('-translate-x-full');$('#profile').onclick=()=>state.user?toast(`${state.user.name||state.user.username} · ${state.user.tier||'free'}`):showAuth();$('#settings').onclick=()=>state.user?toast('Pengaturan lengkap akan tersedia pada panel berikutnya'):showAuth();$('#logout').onclick=async()=>{try{await api('/logout',{method:'POST'})}catch{} location.reload()};$('#auth-close').onclick=()=>$('#auth').classList.add('hidden');$('#auth-switch').onclick=()=>{state.authMode=state.authMode==='login'?'register':'login';showAuth()};$('#auth-form').onsubmit=auth;$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#upload-preview').textContent='Mengunggah '+f.name+'…';$('#upload-preview').className='block text-xs text-slate-400 px-2';try{const b=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result.split(',')[1]);r.onerror=rej;r.readAsDataURL(f)});const d=await api('/upload',{method:'POST',body:JSON.stringify({name:f.name,data:b})});state.uploaded=d;$('#prompt').value+=`\n\n[File: ${d.name||f.name}]`;$('#upload-preview').textContent='✓ '+(d.name||f.name)}catch(err){$('#upload-preview').textContent='Gagal: '+err.message}};
  if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});loadMe().then(ok=>{if(!ok && new URLSearchParams(location.search).get('auth')==='1')showAuth()});
})();