import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from './api';
import type { Message, Session, User } from './types';

const starterPrompts = ['Tinjau kode saya dan temukan masalahnya', 'Buatkan rencana implementasi fitur ini', 'Rangkum dokumen yang saya kirim', 'Bantu saya melakukan riset mendalam'];

function App() {
  const [user, setUser] = useState<User | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [current, setCurrent] = useState<string | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [prompt, setPrompt] = useState(''); const [busy, setBusy] = useState(false); const [sidebar, setSidebar] = useState(false); const [authOpen, setAuthOpen] = useState(false); const [authMode, setAuthMode] = useState<'login'|'register'>('login'); const [error, setError] = useState(''); const [online, setOnline] = useState(true); const endRef = useRef<HTMLDivElement>(null);
  const hasChat = Boolean(current || messages.length);
  const visibleSessions = useMemo(() => sessions, [sessions]);

  useEffect(() => { api.me().then(d => { setUser(d.user); setOnline(true); }).catch(() => { setOnline(false); }); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, busy]);
  async function loadSessions() { try { const d = await api.sessions(); setSessions(d.sessions || []); } catch { setOnline(false); } }
  async function newChat() { if (!user) { setAuthOpen(true); return; } try { const d = await api.createSession(); setSessions(s => [d.session, ...s]); setCurrent(d.session.id); setMessages([]); setSidebar(false); } catch (e) { setError((e as Error).message); } }
  async function switchSession(session: Session) { setCurrent(session.id); setSidebar(false); try { const d = await api.messages(session.id); setMessages(d.messages || []); } catch (e) { setError((e as Error).message); } }
  async function send(text = prompt) { const content = text.trim(); if (!content || busy) return; if (!user) { setAuthOpen(true); return; } let sessionId = current; if (!sessionId) { const d = await api.createSession(); sessionId = d.session.id; setCurrent(sessionId); setSessions(s => [d.session, ...s]); } setPrompt(''); setMessages(m => [...m, { role: 'user', content }]); setBusy(true); try { const response = await api.chat(content, sessionId); if (!response.ok) throw new Error(`Chat gagal (${response.status})`); const source = new EventSource('/api/events'); let answer = ''; setMessages(m => [...m, { role: 'assistant', content: '' }]); source.onmessage = event => { try { const data = JSON.parse(event.data); const delta = data.delta || data.text || ''; if (delta) { answer += delta; setMessages(m => [...m.slice(0, -1), { role: 'assistant', content: answer }]); } if (['agent_end', 'done', 'error'].includes(data.type)) { source.close(); setBusy(false); } } catch { /* ignore non-JSON heartbeat */ } }; source.onerror = () => { source.close(); setBusy(false); }; } catch (e) { setMessages(m => [...m, { role: 'assistant', content: `Terjadi kendala: ${(e as Error).message}` }]); setBusy(false); } }
  async function submitAuth(username: string, password: string, name: string) { try { const d = authMode === 'login' ? await api.login(username, password) : await api.register(username, password, name); setUser(d.user); setAuthOpen(false); setError(''); } catch (e) { setError((e as Error).message); } }
  async function logout() { await api.logout().catch(() => undefined); setUser(null); setSessions([]); setCurrent(null); setMessages([]); }
  return <div className="app-shell min-h-screen">
    <header className="topbar"><div className="brand"><button className="icon-button mobile-only" onClick={() => setSidebar(v => !v)}>☰</button><div className="brand-mark">C</div><div><div className="brand-name">COBLAI</div><div className="brand-sub">CODER WORKSPACE</div></div></div><div className="top-actions"><span className={`connection ${online ? 'ok' : ''}`}><i />{online ? 'Terhubung' : 'Mode lokal'}</span><button className="new-button desktop-only" onClick={newChat}>＋ Chat baru</button><button className="profile-button" onClick={() => user ? setError(`${user.name || user.username} · ${user.tier || 'free'}`) : setAuthOpen(true)}>{(user?.name || user?.username || '?')[0].toUpperCase()}</button></div></header>
    <div className="workspace"><aside className={`sidebar ${sidebar ? 'open' : ''}`}><button className="new-chat" onClick={newChat}>＋ Percakapan baru</button><div className="search"><span>⌕</span><input placeholder="Cari percakapan" /></div><div className="section-label">WORKSPACE <span>{visibleSessions.length}</span></div><nav className="session-list">{visibleSessions.map(s => <button className={`session ${current === s.id ? 'active' : ''}`} key={s.id} onClick={() => switchSession(s)}><span>{s.pinned ? '◆' : '◇'}</span><b>{s.name || 'Percakapan baru'}</b><small>{s.lastUsed ? new Date(s.lastUsed).toLocaleDateString('id-ID', { day: '2-digit', month: 'short' }) : ''}</small></button>)}{!visibleSessions.length && <div className="empty-side">Belum ada percakapan</div>}</nav><div className="sidebar-bottom"><button onClick={() => setError('Pengaturan akan tersedia pada modul berikutnya')}>⚙ Pengaturan & akun</button>{user && <button className="logout" onClick={logout}>Keluar</button>}</div></aside>
    <main className="main"><section className={`conversation ${hasChat ? 'has-chat' : ''}`}>{!hasChat ? <div className="welcome"><span className="eyebrow">✦ RUANG KERJA AI UNTUK MEMBANGUN LEBIH CEPAT</span><h1>Apa yang ingin<br /><em>Anda kerjakan?</em></h1><p>Tulis ide, kirim kode, atau unggah dokumen. COBLAI membantu Anda dari rencana sampai hasil.</p><div className="starter-grid">{starterPrompts.map((p, i) => <button key={p} onClick={() => { setPrompt(p); }}>{p}<strong>{['⌘','↗','▤','⌁'][i]}</strong></button>)}</div></div> : <div className="messages">{messages.map((m, i) => <article className={`message ${m.role}`} key={`${i}-${m.content.slice(0, 8)}`}><div className="message-author">{m.role === 'user' ? 'ANDA' : 'DINDA'}</div><div className="bubble">{m.content || (busy ? 'Dinda sedang bekerja…' : '')}</div></article>)}{busy && <div className="typing"><i /><i /><i /> Dinda sedang bekerja</div>}<div ref={endRef} /></div>}</section><div className="composer-wrap"><form className="composer" onSubmit={e => { e.preventDefault(); send(); }}><textarea value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Tulis pesan untuk Dinda…" rows={1} /><div className="composer-actions"><button type="button" title="Upload">＋</button><span>Enter untuk kirim · Shift+Enter untuk baris baru</span><button className="send" disabled={!prompt.trim() || busy}>↑</button></div></form><small>AI dapat membuat kesalahan. Periksa hasil sebelum digunakan.</small></div></main></div>{error && <button className="toast" onClick={() => setError('')}>{error}</button>}{authOpen && <Auth mode={authMode} onClose={() => setAuthOpen(false)} onSwitch={() => { setAuthMode(v => v === 'login' ? 'register' : 'login'); setError(''); }} onSubmit={submitAuth} error={error} />}</div>;
}

function Auth({ mode, onClose, onSwitch, onSubmit, error }: { mode: 'login'|'register'; onClose: () => void; onSwitch: () => void; onSubmit: (u: string, p: string, n: string) => void; error: string }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); return <div className="modal-backdrop"><form className="auth-card" onSubmit={e => { e.preventDefault(); onSubmit(username, password, name); }}><button type="button" className="close" onClick={onClose}>×</button><span className="eyebrow">COBLAI CODER</span><h2>{mode === 'login' ? 'Masuk ke workspace' : 'Buat akun baru'}</h2>{mode === 'register' && <input value={name} onChange={e => setName(e.target.value)} placeholder="Nama Anda" /> }<input required value={username} onChange={e => setUsername(e.target.value)} placeholder="Username atau email" /><input required type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" /><button className="primary">Lanjutkan</button>{error && <p className="error">{error}</p>}<button type="button" className="switch" onClick={onSwitch}>{mode === 'login' ? 'Belum punya akun? Daftar' : 'Sudah punya akun? Masuk'}</button></form></div>; }

export { App };
