import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from './api';
import { Tools } from './Tools';
import type { Message, Session, User } from './types';

const starterPrompts = ['Tinjau kode saya dan temukan masalahnya', 'Buatkan rencana implementasi fitur ini', 'Rangkum dokumen yang saya kirim', 'Bantu saya melakukan riset mendalam'];

function App() {
  const [user, setUser] = useState<User | null>(null); const [toolsOpen, setToolsOpen] = useState(false); const [projectId, setProjectId] = useState<string | null>(null); const [workspaceId, setWorkspaceId] = useState<string | null>(null); const [settingsOpen, setSettingsOpen] = useState(false); const [sessions, setSessions] = useState<Session[]>([]); const [current, setCurrent] = useState<string | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [prompt, setPrompt] = useState(''); const [busy, setBusy] = useState(false); const [sidebar, setSidebar] = useState(false); const [authOpen, setAuthOpen] = useState(false); const [authMode, setAuthMode] = useState<'login'|'register'>('login'); const [error, setError] = useState(''); const [online, setOnline] = useState(true); const [notice, setNotice] = useState(''); const [query, setQuery] = useState(''); const [activeRun, setActiveRun] = useState<string | null>(null); const endRef = useRef<HTMLDivElement>(null);
  const hasChat = Boolean(current || messages.length);
  const visibleSessions = useMemo(() => sessions.filter(s => (s.name || '').toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => Number(Boolean(b.pinned)) - Number(Boolean(a.pinned))), [sessions, query]);

  useEffect(() => { api.me().then(d => { setUser(d.user); setOnline(true); loadSessions().catch(() => setOnline(false)); }).catch(() => { setOnline(false); }); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, busy]);
  async function loadSessions() { try { const ws = (await api.workspaces())[0]; if (!ws) return; setWorkspaceId(ws.id); const projects = (await api.projects(ws.id)); const project = projects[0]; if (!project) return; setProjectId(project.id); const d = await api.sessions(project.id); setSessions(d || []); } catch { setOnline(false); } }
  async function renameSession(s: Session) { const title = window.prompt('Judul percakapan', s.name || ''); if (title === null) return; try { await api.renameSession(s.id, title.trim() || 'Percakapan baru', s.pinned); await loadSessions(); } catch (e) { setError((e as Error).message); } }
  async function pinSession(s: Session) { try { await api.renameSession(s.id, s.name || 'Percakapan baru', !s.pinned); await loadSessions(); } catch (e) { setError((e as Error).message); } }
  async function removeSession(s: Session) { if (!window.confirm(`Hapus percakapan "${s.name || 'Percakapan baru'}"?`)) return; try { await api.deleteSession(s.id); if (current === s.id) { setCurrent(null); setMessages([]); } await loadSessions(); setNotice('Percakapan dihapus.'); } catch (e) { setError((e as Error).message); } }
  async function exportSession(s: Session) { try { const payload = await api.exportSession(s.id); const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `${(s.name || 'percakapan').replace(/[^\w.-]+/g, '-')}.json`; link.click(); URL.revokeObjectURL(url); } catch (e) { setError((e as Error).message); } }
  async function importSession(file: File) {
    if (!projectId) { setError('Proyek belum siap.'); return; }
    try {
      const payload = JSON.parse(await file.text());
      const imported = await api.importSession(projectId, { title: payload?.conversation?.title ?? file.name, messages: payload?.messages ?? [] });
      await loadSessions(); setNotice(`Percakapan "${imported.conversation.title}" diimpor.`);
    } catch (e) { setError(`Impor gagal: ${(e as Error).message}`); }
  }
  async function stopRun() { if (!activeRun) return; try { await api.cancelRun(activeRun); setNotice('Permintaan berhenti dikirim.'); } catch (e) { setError((e as Error).message); } }

  async function newChat() { if (!user) { setAuthOpen(true); return; } try { if (!projectId) { await loadSessions(); } const d = await api.createSession(projectId!, 'Percakapan baru'); setSessions(s => [d.conversation, ...s]); setCurrent(d.conversation.id); setMessages([]); setSidebar(false); } catch (e) { setError((e as Error).message); } }
  async function switchSession(session: Session) { setCurrent(session.id); setSidebar(false); try { const d = await api.messages(session.id); setMessages(d.messages || []); } catch (e) { setError((e as Error).message); } }
  const [model, setModel] = useState('');
  const [modelOptions, setModelOptions] = useState<{ value: string; label: string }[]>([]);
  useEffect(() => {
    // The catalogue comes from the engine itself, so an empty list means the picker stays hidden.
    api.models().then(data => {
      const options = [{ value: '', label: data.default.model ? `Bawaan (${data.default.model})` : 'Model bawaan' }].concat(data.models.map(row => ({ value: row.model, label: `${row.provider} · ${row.model}` })));
      setModelOptions(options);
      const stored = localStorage.getItem('coblai.model') || '';
      if (stored && data.models.some(row => row.model === stored)) setModel(stored);
    }).catch(() => setModelOptions([]));
  }, []);

  async function send(text = prompt) { const content = text.trim(); if (!content || busy) return; if (!user) { setAuthOpen(true); return; } let sessionId = current; if (!sessionId) { await newChat(); sessionId = current; } if (!sessionId) return; setPrompt(''); setMessages(m => [...m, { role: 'user', content }]); setBusy(true); try { const response = await api.sendMessage(sessionId, content, model || undefined); setActiveRun(response.run.id); setMessages(m => [...m, { role: 'assistant', content: '' }]); const source = new EventSource(`/api/v1/runs/${response.run.id}/events`); let answer = ''; source.onmessage = event => { try { const data = JSON.parse(event.data); const delta = data.data?.delta || data.data || ''; if (data.type === 'text' && typeof delta === 'string') { answer += delta; setMessages(m => [...m.slice(0, -1), { role: 'assistant', content: answer }]); } if (['completed', 'failed', 'cancelled'].includes(data.type)) { source.close(); setBusy(false); setActiveRun(null); } } catch { /* ignore heartbeat */ } }; source.onerror = () => { source.close(); setBusy(false); setActiveRun(null); }; } catch (e) { setMessages(m => [...m, { role: 'assistant', content: `Terjadi kendala: ${(e as Error).message}` }]); setBusy(false); } }
  async function submitAuth(username: string, password: string, name: string) { try { const d = authMode === 'login' ? await api.login(username, password) : await api.register(username, password, name); setUser(d.user); setAuthOpen(false); setError(''); } catch (e) { setError((e as Error).message); } }
  async function logout() { await api.logout().catch(() => undefined); setUser(null); setSessions([]); setCurrent(null); setMessages([]); }
  return <div className="app-shell min-h-screen">
    <header className="topbar"><div className="brand"><button className="icon-button mobile-only" onClick={() => setSidebar(v => !v)}>☰</button><div className="brand-mark">C</div><div><div className="brand-name">COBLAI</div><div className="brand-sub">CODER WORKSPACE</div></div></div><div className="top-actions"><span className={`connection ${online ? 'ok' : ''}`}><i />{online ? 'Terhubung' : 'Mode lokal'}</span><button className="new-button desktop-only" onClick={newChat}>＋ Chat baru</button><button className="profile-button" onClick={() => user ? setSettingsOpen(true) : setAuthOpen(true)}>{(user?.displayName || user?.name || user?.email || '?')[0].toUpperCase()}</button></div></header>
    <div className="workspace"><aside className={`sidebar ${sidebar ? 'open' : ''}`}><button className="new-chat" onClick={newChat}>＋ Percakapan baru</button><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari percakapan" /></div><div className="section-label">WORKSPACE <span>{visibleSessions.length}</span></div><nav className="session-list">{visibleSessions.map(s => <div className={`session-row ${current === s.id ? 'active' : ''}`} key={s.id}><button className={`session ${current === s.id ? 'active' : ''}`} onClick={() => switchSession(s)}><span>{s.pinned ? '◆' : '◇'}</span><b>{s.name || 'Percakapan baru'}</b><small>{s.lastUsed ? new Date(s.lastUsed).toLocaleDateString('id-ID', { day: '2-digit', month: 'short' }) : ''}</small></button><div className="session-actions"><button title="Ganti nama" onClick={() => renameSession(s)}>✎</button><button title={s.pinned ? 'Lepas pin' : 'Pin'} onClick={() => pinSession(s)}>◆</button><button title="Ekspor" onClick={() => exportSession(s)}>↓</button><button title="Hapus" onClick={() => removeSession(s)}>✕</button></div></div>)}{!visibleSessions.length && <div className="empty-side">Belum ada percakapan</div>}</nav><div className="sidebar-bottom"><button onClick={() => user ? setToolsOpen(true) : setAuthOpen(true)}>▦ Knowledge & workflow</button><button onClick={() => user ? setSettingsOpen(true) : setAuthOpen(true)}>⚙ Pengaturan & akun</button>{user && <button className="logout" onClick={logout}>Keluar</button>}</div></aside>
    <main className="main"><section className={`conversation ${hasChat ? 'has-chat' : ''}`}>{!hasChat ? <div className="welcome"><span className="eyebrow">✦ RUANG KERJA AI UNTUK MEMBANGUN LEBIH CEPAT</span><h1>Apa yang ingin<br /><em>Anda kerjakan?</em></h1><p>Tulis ide, kirim kode, atau unggah dokumen. COBLAI membantu Anda dari rencana sampai hasil.</p><div className="starter-grid">{starterPrompts.map((p, i) => <button key={p} onClick={() => { setPrompt(p); }}>{p}<strong>{['⌘','↗','▤','⌁'][i]}</strong></button>)}</div></div> : <div className="messages">{messages.map((m, i) => <article className={`message ${m.role}`} key={`${i}-${m.content.slice(0, 8)}`}><div className="message-author">{m.role === 'user' ? 'ANDA' : 'DINDA'}</div><div className="bubble">{m.content || (busy ? 'Dinda sedang bekerja…' : '')}</div></article>)}{busy && <div className="typing"><i /><i /><i /> Dinda sedang bekerja</div>}<div ref={endRef} /></div>}</section><div className="composer-wrap"><form className="composer" onSubmit={e => { e.preventDefault(); send(); }}><textarea value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Tulis pesan untuk Dinda…" rows={1} /><div className="composer-actions">{modelOptions.length > 0 && <label className="model-picker" title="Model AI untuk pesan berikutnya">⚙<select value={model} onChange={e => { setModel(e.target.value); localStorage.setItem('coblai.model', e.target.value); }}>{modelOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}<label className="upload-button" title="Impor percakapan (JSON)">＋<input type="file" accept=".json" onChange={e => { const file = e.target.files?.[0]; if (file) void importSession(file); e.target.value = ''; }} /></label>{busy && <button type="button" className="stop" title="Hentikan" onClick={stopRun}>■ Berhenti</button>}<span>Enter untuk kirim · Shift+Enter untuk baris baru</span><button className="send" disabled={!prompt.trim() || busy}>↑</button></div></form><small>AI dapat membuat kesalahan. Periksa hasil sebelum digunakan.</small></div></main></div>{error && <button className="toast" onClick={() => setError('')}>{error}</button>}{notice && <button className="toast notice-toast" onClick={() => setNotice('')}>{notice}</button>}{toolsOpen && projectId && <Tools projectId={projectId} workspaceId={workspaceId} onClose={() => setToolsOpen(false)} />} {settingsOpen && user && <Settings user={user} onClose={() => setSettingsOpen(false)} onLogout={logout} />} {authOpen && <Auth mode={authMode} onClose={() => setAuthOpen(false)} onSwitch={() => { setAuthMode(v => v === 'login' ? 'register' : 'login'); setError(''); }} onSubmit={submitAuth} error={error} />}</div>;
}

function Settings({ user, onClose, onLogout }: { user: User; onClose: () => void; onLogout: () => void }) { return <div className="modal-backdrop"><section className="auth-card settings-card"><button type="button" className="close" onClick={onClose}>×</button><span className="eyebrow">AKUN & WORKSPACE</span><h2>Pengaturan</h2><label>Nama tampilan<input readOnly value={user.displayName || user.name || ''} /></label><label>Email<input readOnly value={user.email} /></label><div className="settings-meta"><span>Status akun</span><strong>Aktif</strong></div><div className="settings-meta"><span>Role</span><strong>{user.role || 'member'}</strong></div><button type="button" className="primary" onClick={onClose}>Selesai</button><button type="button" className="switch" onClick={onLogout}>Keluar dari akun</button></section></div>; }

function Auth({ mode, onClose, onSwitch, onSubmit, error }: { mode: 'login'|'register'; onClose: () => void; onSwitch: () => void; onSubmit: (u: string, p: string, n: string) => void; error: string }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); return <div className="modal-backdrop"><form className="auth-card" onSubmit={e => { e.preventDefault(); onSubmit(username, password, name); }}><button type="button" className="close" onClick={onClose}>×</button><span className="eyebrow">COBLAI CODER</span><h2>{mode === 'login' ? 'Masuk ke workspace' : 'Buat akun baru'}</h2>{mode === 'register' && <input value={name} onChange={e => setName(e.target.value)} placeholder="Nama Anda" /> }<input required value={username} onChange={e => setUsername(e.target.value)} placeholder="Username atau email" /><input required type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" /><button className="primary">Lanjutkan</button>{error && <p className="error">{error}</p>}<button type="button" className="switch" onClick={onSwitch}>{mode === 'login' ? 'Belum punya akun? Daftar' : 'Sudah punya akun? Masuk'}</button></form></div>; }

export { App };
